### ISSUE TITLE
Save perma.cc short URLs 

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/archivr#1]
Currently we're saving //perma-archives.org/warc/G5EH-JA9M/http://www.google.com
Could we instead (or in addition? What do you think?) write the short URL, perma.cc/G5EH-JA9M to the data frame?

**Comment by greebie** [comment]
Definitely.  This issue will be the last save to master (I'll work on it tonight).

**Comment by greebie** [comment]
Resolved with https://github.com/QualitativeDataRepository/archivr/commit/06a66c576bd9a71663f711d3dc6c3cefe9b981b9

Closing.
