### ISSUE TITLE
Allow specifying perma.cc folder

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/archivr#10]
I think(!) the right way to do this is to take a folder name and then search through all top-level folders whether that name exists. If it does, save to that folder. If it doesn't, create a new one.

Open for other proposals, but it'd be very helpful if we could save to folders in perma.cc (since we use one folder/project)

**Comment by greebie** [comment]
This should not be a problem, as the api has a folder option.

**Comment by greebie** [comment]
Okay - unfortunately, perma.cc does not search by folder name, you require an id.

What I think I can do is provide a "get_perma_cc_folders" function to display the ids of the various folders as a reference for now. Building in a search would be nice, but we can look this for a 0.1.1.

**Comment by adam3smith** [comment]
yeah, I saw that in the API -- I'm OK with just being able to get the list and then using the id.
The way I had envisioned the search was to get JSON will all folder data and then search through that locally.

**Comment by adam3smith** [comment]
Currently having some problems:
1) loading the script via `source` I get 

```
Error in get_default_folder() : 
  could not find function "get_default_folder"
```
and no functions load. If I run the script, all functions load, but the same error still comes up under `.folder_id`. The `get_default_folder()` function shows up and looks right to me in the environment.

2. Running `folders <- get_folder_ids()` , I get a df with only one entry, Personal Links. Running
https://api.perma.cc/v1/folders?api_key=XXXX
I get 

```
"objects": [
        {
            "id": 26813,
            "name": "Personal Links",
            "parent": null,
            "has_children": false,
            "path": "26813",
            "organization": null
        },
        {
            "id": 25656,
            "name": "Qualitative Data Repository",
            "parent": null,
            "has_children": true,
            "path": "25656",
            "organization": 978
        }
    ]
```
i.e. also the QDR folder. 

After that, `get_subfolder_id("25656")` 
`set_folder_id("ID")`
and
`archiv` works perfectly and saves to the right folder

**Comment by greebie** [comment]
Hi Sebastian. Apologies for the delay. I did take a look at this and I think I have the correct solution (pushed to the PR), but I have not been able to test it because I cannot figure out how to add a folder to the root node (only the "personal links" folder).

**Comment by adam3smith** [comment]
Both issues are now fixed and everything is working as desired, thanks!
