### ISSUE TITLE
Feature: option to exclude URL patters

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/archivr#12]
Mostly we can assume those to be permanent, no need to extra archive them.

(this needn't be in the first release; just keeping track of ideas)

**Comment by greebie** [comment]
Sounds good.  Basically, it would just require a flag, some conditional logic and a new regex.

**Comment by adam3smith** [comment]
Have thought about this more -- the way to do this is to add an `exclude` parameter to the extract and archiv functions that takes a regular expression and doesn't archive those, so e.g. 
`archiv.fromText("filepath", exclude="^https?:\\/\\/doi\\.org\\/")` would exclude DOIs

**Comment by adam3smith** [comment]
implemented in #31
