### ISSUE TITLE
Allow saving to WayBackMachine instead of perma.cc

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/archivr#2]
I'm pretty sure that's possible and it'd be really nice because most "regular" users won't have a perma.cc account.

This should be a preference, of course. I'd default to WBM because it doesn't require an API key

**Comment by greebie** [comment]
Thanks for adding the issues, Sebastian. I'll probably get to these tonight. It's been a restful holiday.  :)

FYI - I expect to add these features in separate branches and using a PR. Would you be okay with merging after testing? I'm assuming that you have some basic functionality right now, and I want you to be able to track and blame if something breaks along the way.

**Comment by adam3smith** [comment]
Sounds good, yes

**Comment by greebie** [comment]
(Just for tracking.) It's pretty easy to save to wayback, but the callbacks will likely take some time if the lists are large. Wrapping the calls in a promise may help reduce the time it takes to save the items, but it'd be good to monitor.

An alternative solution is just to commit the save, and then do a simple available? search.
