### ISSUE TITLE
Add Code Examples for CRAN

### ISSUE THREAD

**Issue by greebie** [QualitativeDataRepository/archivr#21]
Related to #14 - CRAN rejected out submission because we do not have any inline examples in the code.

**Comment by adam3smith** [comment]
Starting work on this

**Comment by greebie** [comment]
Thanks for the great work here @adam3smith !

**Comment by adam3smith** [comment]
Yay! You'll resubmit to CRAN? If there's a way to CC me, I'd be happy to be part of this -- both to learn about the process and because I'll likely be able to address smaller issues.
