### ISSUE TITLE
More Elegant Exit when result returns NULL

### ISSUE THREAD

**Issue by greebie** [QualitativeDataRepository/archivr#29]
Currently, archiv attempts to create a dataframe from a results set from either Wayback or Perma.cc. When there is no existing website to correspond to a link, it returns a boilerplate "NOT A URL" and includes it in the results.

We also uncovered some cases via #28 where an empty result produces NULL and this results in an error.

We need a more elegant approach to NULL values across the board. First suggestion is that NULLs are removed from results dataframe, and stored in some other structure (a list). We could create some form of results object to do this, or just output errors to log.  (I think I prefer the latter, since it would give the user and possibly later functions to do additional data wrangling with poorly formed urls (cf discussion in #18 about optional url cleaning utilities)).

**Comment by mccallc** [comment]
implemented pruning of non-existent results in returned data.frame. Failed searches output messages directly to the console with `message()`.
