### ISSUE TITLE
CRAN Feedback

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/archivr#33]
THanks,

The Description field is intended to be a (one paragraph) description of
what the package does and why it may be useful. Please elaborate.

Please always write TRUE and FALSE instead of T and F.

You write information messages to the console that cannot be easily
suppressed.
It is more R like to generate objects that can be used to extract the
information a user is interested in, and then print() that object.
Instead of print()/cat() rather use message()/warning()  or
if(verbose)cat(..) if you really have to write text to the console.
(except for print() and summary() functions)
F.i.: view_archiv.R

Please fix and resubmit, and document what was changed in the submission
comments.

Best,

**Comment by mccallc** [comment]
- T to TRUE, commit b99cd70d64e5060cb4da7fd557f1ebac86bbdd52
- print() changed to message()/warning(), commit b0c80e345680b910f304272f318ef94903805d08
- Description extended, commit 5d3a7452f47b93d623a2a62a317cfb89404ae227
